### ISSUE TITLE
why sudo?

### ISSUE THREAD

**Issue by thuvh** [maytinhdibo/uetbuildjava-linux#1]
trong $HOME, tạo thư mục bin rồi cho uetjava vào bin thì không cần đến sudo

**Comment by maytinhdibo** [comment]
Em định để vậy là cho all user luôn.

**Comment by thuvh** [comment]
quan điểm của anh là cái tool này của em là "cá nhân" sẽ dùng nhiều hơn, và máy cá nhân của em thì chỉ em dùng là chính thôi. Cuối cùng là nếu em tìm hiểu về [dotfile](https://dotfiles.github.io/) thì em sẽ thấy là thay vì viết script install, e có thể nhét luôn vào $HOME/bin hoặc đại loại vậy
